name: Lint

on: 
  workflow_dispatch:
  #push
  #pull_request:

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4 # Check out the repository first.

      - name: Install TypeScript dependencies
        working-directory: frontend
        run: |
          npm i -g pnpm
          pnpm i --frozen-lockfile --dangerously-allow-all-builds

      - name: Run prettier (TypeScript)
        working-directory: frontend
        run: pnpm run lint
