name: Type Check

on: 
  workflow_dispatch:
  #push
  #pull_request:

jobs:
  typecheck:
    name: Run type checkers
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4 # Check out the repository first.

      - name: Set up NodeJS 20 💎
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Python 3.11.7 🐍
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.7"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false

      - name: Install Python dependencies ⬇️
        working-directory: backend
        run: poetry install --no-interaction

      - name: Install TypeScript dependencies
        working-directory: frontend
        run: |
          npm i -g pnpm
          pnpm i --frozen-lockfile --dangerously-allow-all-builds

      - name: Run pyright (Python)
        uses: jakebailey/pyright-action@v1
        with:
          python-version: "3.10.6"
          no-comments: true
          working-directory: backend

      - name: Run tsc (TypeScript)
        working-directory: frontend
        run: pnpm run typecheck
